[project]
name = "shorturl"
version = "2.0.0.dev1"
description = "A python application which converts long urls to short urls"
readme = "README.md"
authors = [
    { name = "Rohan Prasen Kedari", email = "rohanprasenkedari@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.143.0",
    "psycopg2-binary>=2.9.13",
    "python-dotenv>=1.2.4",
    "redis>=8.1.0",
    "uvicorn>=0.54.0",
]

[project.scripts]
shorturl = "app.__init__:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.14.0"]
build-backend = "uv_build"

[tool.uv-build]
packages = ["app"]

[tool.uv.build-backend]
module-root = ""
module-name = "app"

[dependency-groups]
dev = [
    "pre-commit>=4.6.2",
    "pytest>=9.1.1",
    "ruff>=0.16.10",
]
