[project]
name = "shorturl"
version = "0.1.0"
description = "A python application which converts long urls to short urls"
readme = "README.md"
authors = [
    { name = "Rohan Prasen Kedari", email = "rohanprasenkedari@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
shorturl = "app.main:main"

[build-system]
requires = ["uv_build>=0.12.23,<0.13.0"]
build-backend = "uv_build"

[tool.uv-build]
packages = ["app"]

[tool.uv.build-backend]
module-root = ""
module-name = "app"
